### ISSUE TITLE
Connection Error: "the given key 'minMoney' was not present in the dictionary at System.Collections.Generic.Dictionary' 

### ISSUE THREAD

**Issue by Bathinjan** [Awesomeness278/APLC#4]
I can connect to the Archipelago webserver via '/connect archipelago:[port number]' command in the LC console, and then submitting the player name. 

However, the LC console throws the error below, and while Arch chests show up in the world, the checks do not get updated in the webserver tracker / console. Additionally, items from other worlds are not sent to the LC player. 

I am using the YAML and .apworld files, as well as all their default values, from this Github directory.

![error](https://github.com/Awesomeness278/APLC/assets/83847977/0575af97-7006-4e5e-ad5a-9631d0a378cd)

**Comment by Awesomeness278** [comment]
I should probably add some error handling so that if you use old ap saves, it will default to a default value

**Comment by Bathinjan** [comment]
I fixed the issue and can now connect - 
For anyone experiencing the same problem, here's what fixed it for me:

 - completely uninstall / remove all Archipelago folders & files
 
 - re-install the [newest version of Archipelago](https://github.com/ArchipelagoMW/Archipelago/releases)
 
 - open r2modman & delete your old mod profile
 
 - create a brand new APLC mod profile
 
 - re-download the APLC mod - as of this post, 19 Jan 2024, make sure you have **5 dependencies with no updates**
 
 - make sure there are **no other mods** on the profile until you confirm you can connect to APLC properly
 
 - load into the game & create a BRAND NEW SAVE FILE (don't play on an old one!)
 
 - once you load in, type a forward slash (/) to bring up the LC console, and then type "/connect archipelago.gg:[archipelago port #]" 
 
 - (note: the archipelago port number can be found at the top of the "room" webpage generated when you uploaded the file to "host game")
 
 - when you get a message that says "Enter player name:", type a forward slash again and enter the Lethal Company player name from the room generated from Host Game (if you pulled the files directly from this Github repo and didn't change anything, the name will be "LethalCompany"). This is **case sensitive**
 
 - you should get a white message that says you connected to the APLC server
